#!/bin/sh
if [ "$1" = "--help" ]
then
    echo "Generate custom WSL distributions with libTAS preinstalled"
    echo
    echo "Usage: ./libTAS-wsl [image] [version]"
    echo "  image is the name of a Docker image (default: ubuntu:24.04)"
    echo "  version is a libTAS release version (default: 1.4.7)"
    echo
    echo "Usage: ./libTAS-wsl pcem [lversion] [pversion]"
    echo "  lversion is a libTAS release version (default: 1.4.7)"
    echo "  pversion is a PCem release version from"
    echo "    https://github.com/TASEmulators/pcem/releases (default: 17+st-1)"
    echo
    echo "Usage: ./libTAS-wsl ruffle [rversion] [image] [lversion]"
    echo "  rversion is a Ruffle nightly build version from"
    echo "    https://github.com/ruffle-rs/ruffle/releases (required)"
    echo "  image is the name of a Docker image (default: ubuntu:24.04)"
    echo "  lversion is a libTAS release version (default: 1.4.7)"
    echo
    echo "Usage: ./libTAS-wsl interim [image]"
    echo "  image is the name of a Docker image (default: ubuntu:24.04)"
    return

elif [ "$1" = "ruffle" ] && [ "$2" = "" ]
then
    echo "Usage: ./libTAS-wsl ruffle [rversion] [image] [lversion]"
    echo "  rversion is a Ruffle nightly build version from"
    echo "    https://github.com/ruffle-rs/ruffle/releases (required)"
    echo "  image is the name of a Docker image (default: ubuntu:24.04)"
    echo "  lversion is a libTAS release version (default: 1.4.7)"
    return
fi

platform=${1:-ubuntu:24.04}
version=${2:-1.4.7}
dockerFile="Dockerfile"
dockerName="libtas-wsl"

if [ "$1" = "pcem" ]
then
    platform="ubuntu:22.04"

elif [ "$1" = "ruffle" ]
then
    platform=${3:-ubuntu:24.04}
    version=${4:-1.4.7}

elif [ "$1" = "interim" ]
then
    platform=${2:-ubuntu:24.04}
    dockerFile="interim.Dockerfile"
    dockerName="libtas-wsl-interim"
fi

docker build \
    --build-arg baseImage="$platform" \
    --build-arg releaseVersion="$version" \
    -f "$dockerFile" \
    -t "$dockerName" \
    setup

if [ "$1" = "pcem" ]
then
    version=${3:-17+st-1}
    dockerName="libtas-wsl-pcem"

    docker build \
        --build-arg releaseVersion="$version" \
        -t "$dockerName" \
        - < pcem.Dockerfile

elif [ "$1" = "ruffle" ]
then
    version=$2
    dockerName="libtas-wsl-ruffle"

    day=$version
    month=${day%-*}
    year=${month%-*}
    day=${day##*-}
    month=${month##*-}
    year=${year##*-}
    assetFilename="ruffle-nightly-${year}_${month}_$day-linux-x86_64.tar.gz"

    docker build \
        --build-arg releaseTag="$version" \
        --build-arg assetFilename="$assetFilename" \
        -f ruffle.Dockerfile \
        -t "$dockerName" \
        setup
fi

docker create --name "$dockerName" -it "$dockerName"

docker export "$dockerName" | \
    tar --delete etc/resolv.conf | \
    gzip --best > "libTAS.wsl"

docker container rm "$dockerName"
