name: Build Release

on:
  schedule:
    - cron: '40 1 * * 5'
  workflow_dispatch:

jobs:
  fetch_ruffle_version:
    name: Fetch Ruffle Version
    runs-on: ubuntu-latest
    outputs:
      ruffle_version: ${{ steps.fetch.outputs.tag }}
    steps:
      - name: Fetch latest release tag
        id: fetch
        run: |
          url=https://api.github.com/repos/ruffle-rs/ruffle/releases
          tag=$(curl $url | jq -r '.[0].tag_name')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Check tag
        if: ${{ steps.fetch.outputs.tag == 'null' }}
        uses: actions/github-script@v9
        with:
          script: core.setFailed('Fetch failed for Ruffle version')

  build_release_matrix:
    name: Build and Test
    needs: fetch_ruffle_version
    strategy:
      matrix:
        libtas_version: [1.4.5, 1.4.6, 1.4.7]
        pcem: [false, true]
        ruffle: [false, true]
        include:
          - pcem: false
            docker_image: ubuntu:24.04
          - pcem: true
            pcem_version: 17+st-1
          - ruffle: true
            ruffle_version: >-
              ${{ needs.fetch_ruffle_version.outputs.ruffle_version }}
        exclude:
          - libtas_version: 1.4.7
            pcem: true
          - pcem: true
            ruffle: true
    uses: StephenCWills/libTAS-wsl/.github/workflows/build-and-test.yml@main
    with:
      libtas_version: ${{ matrix.libtas_version }}
      docker_image: ${{ matrix.docker_image }}
      pcem_version: ${{ matrix.pcem_version }}
      ruffle_version: ${{ matrix.ruffle_version }}

  release:
    needs: build_release_matrix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Download all artifacts
        uses: actions/download-artifact@v8

      - name: Post release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          body: Weekly updates using the latest Docker images
          make_latest: true
          files: '*/*.wsl'
