name: Build and Test

on:
  workflow_call:
    inputs:
      libtas_version:
        required: true
        type: string
      docker_image:
        default: ''
        required: false
        type: string
      pcem_version:
        default: ''
        required: false
        type: string

env:
  ARTIFACT_NAME: ${{ inputs.pcem_version == '' && format('libTAS-{0}_amd64.wsl', inputs.libtas_version) || format('libTAS-{0}_PCem-{1}_amd64.wsl', inputs.libtas_version, inputs.pcem_version) }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ inputs.docker_image }}
      LIBTAS_VERSION: ${{ inputs.libtas_version }}
      PCEM_VERSION: ${{ inputs.pcem_version }}
    steps:
      - name: Check out libTAS-wsl
        uses: actions/checkout@v6

      - name: Generate libTAS.wsl
        if: ${{ inputs.libtas_version != 'interim' && inputs.pcem_version == '' }}
        run: |
          ./libTAS-wsl "$DOCKER_IMAGE" "$LIBTAS_VERSION" &&
          mv libTAS.wsl "$ARTIFACT_NAME"

      - name: Generate libTAS.wsl with PCem
        if: ${{ inputs.pcem_version != '' }}
        run: |
          ./libTAS-wsl pcem "$LIBTAS_VERSION" "$PCEM_VERSION" &&
          mv libTAS.wsl "$ARTIFACT_NAME"

      - name: Generate libTAS.wsl with interim version
        if: ${{ inputs.libtas_version == 'interim' }}
        run: |
          ./libTAS-wsl interim "$DOCKER_IMAGE" &&
          mv libTAS.wsl "$ARTIFACT_NAME"

      - name: Upload libTAS.wsl
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.ARTIFACT_NAME }}
          archive: false

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download libTAS.wsl
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Install libTAS.wsl distribution
        run: |
          wsl --install --from-file $env:ARTIFACT_NAME --no-launch
          $path = "\\wsl.localhost\libTAS\etc\oobe.sh"
          $prompt = "read -p 'Enter new UNIX username: ' username"
          $passwd = "/usr/bin/passwd `"\`$username`""
          $chpasswd = "echo TAS:libtas | /usr/sbin/chpasswd"
          $aptinstall = "apt-get -y install"
          $nointinstall = "DEBIAN_FRONTEND=noninteractive $aptinstall"
          $oobe = Get-Content -Raw $path
          $oobe = $oobe -replace $prompt, "username=TAS"
          $oobe = $oobe -replace $passwd, $chpasswd
          $oobe = $oobe -replace $aptinstall, $nointinstall
          $oobe | Set-Content -NoNewLine $path
          wsl -d libTAS
