name: Build Interim

on:
  workflow_dispatch:

jobs:
  build_interim:
    name: Build and Test
    uses: StephenCWills/libTAS-wsl/.github/workflows/build-and-test.yml@main
    with:
      libtas_version: interim
      docker_image: ubuntu:24.04
